// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.ssvictor.netty.netty_protobuf;

public final class DataInfo {
  private DataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ssvictor.netty.netty_protobuf.MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.ssvictor.netty.netty_protobuf.MyMessage.DataType data_type = 1;</code>
     */
    boolean hasDataType();
    /**
     * <code>required .com.ssvictor.netty.netty_protobuf.MyMessage.DataType data_type = 1;</code>
     */
    com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType getDataType();

    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
     */
    boolean hasTeacher();
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
     */
    com.ssvictor.netty.netty_protobuf.DataInfo.Teacher getTeacher();
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
     */
    com.ssvictor.netty.netty_protobuf.DataInfo.TeacherOrBuilder getTeacherOrBuilder();

    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
     */
    boolean hasStudent();
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
     */
    com.ssvictor.netty.netty_protobuf.DataInfo.Student getStudent();
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
     */
    com.ssvictor.netty.netty_protobuf.DataInfo.StudentOrBuilder getStudentOrBuilder();

    public com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code com.ssvictor.netty.netty_protobuf.MyMessage}
   */
  public  static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ssvictor.netty.netty_protobuf.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      dataType_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType value = com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.ssvictor.netty.netty_protobuf.DataInfo.Student.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.ssvictor.netty.netty_protobuf.DataInfo.Student.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.class, com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code com.ssvictor.netty.netty_protobuf.MyMessage.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PersonType = 1;</code>
       */
      PersonType(1),
      /**
       * <code>TeacherType = 2;</code>
       */
      TeacherType(2),
      ;

      /**
       * <code>PersonType = 1;</code>
       */
      public static final int PersonType_VALUE = 1;
      /**
       * <code>TeacherType = 2;</code>
       */
      public static final int TeacherType_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 1: return PersonType;
          case 2: return TeacherType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.ssvictor.netty.netty_protobuf.MyMessage.DataType)
    }

    private int bitField0_;
    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      TEACHER(2),
      STUDENT(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return TEACHER;
          case 3: return STUDENT;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>required .com.ssvictor.netty.netty_protobuf.MyMessage.DataType data_type = 1;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .com.ssvictor.netty.netty_protobuf.MyMessage.DataType data_type = 1;</code>
     */
    public com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType result = com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType.valueOf(dataType_);
      return result == null ? com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType.PersonType : result;
    }

    public static final int TEACHER_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
     */
    public boolean hasTeacher() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
     */
    public com.ssvictor.netty.netty_protobuf.DataInfo.Teacher getTeacher() {
      if (dataBodyCase_ == 2) {
         return (com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_;
      }
      return com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.getDefaultInstance();
    }
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
     */
    public com.ssvictor.netty.netty_protobuf.DataInfo.TeacherOrBuilder getTeacherOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_;
      }
      return com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.getDefaultInstance();
    }

    public static final int STUDENT_FIELD_NUMBER = 3;
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
     */
    public boolean hasStudent() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
     */
    public com.ssvictor.netty.netty_protobuf.DataInfo.Student getStudent() {
      if (dataBodyCase_ == 3) {
         return (com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_;
      }
      return com.ssvictor.netty.netty_protobuf.DataInfo.Student.getDefaultInstance();
    }
    /**
     * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
     */
    public com.ssvictor.netty.netty_protobuf.DataInfo.StudentOrBuilder getStudentOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_;
      }
      return com.ssvictor.netty.netty_protobuf.DataInfo.Student.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage)) {
        return super.equals(obj);
      }
      com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage other = (com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage) obj;

      if (hasDataType() != other.hasDataType()) return false;
      if (hasDataType()) {
        if (dataType_ != other.dataType_) return false;
      }
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getTeacher()
              .equals(other.getTeacher())) return false;
          break;
        case 3:
          if (!getStudent()
              .equals(other.getStudent())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataType()) {
        hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + dataType_;
      }
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + TEACHER_FIELD_NUMBER;
          hash = (53 * hash) + getTeacher().hashCode();
          break;
        case 3:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ssvictor.netty.netty_protobuf.MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ssvictor.netty.netty_protobuf.MyMessage)
        com.ssvictor.netty.netty_protobuf.DataInfo.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.class, com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.Builder.class);
      }

      // Construct using com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_descriptor;
      }

      @java.lang.Override
      public com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage getDefaultInstanceForType() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage build() {
        com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage buildPartial() {
        com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage result = new com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (teacherBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = teacherBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (studentBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = studentBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage) {
          return mergeFrom((com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage other) {
        if (other == com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.getDefaultInstance()) return this;
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        switch (other.getDataBodyCase()) {
          case TEACHER: {
            mergeTeacher(other.getTeacher());
            break;
          }
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDataType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dataType_ = 1;
      /**
       * <code>required .com.ssvictor.netty.netty_protobuf.MyMessage.DataType data_type = 1;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .com.ssvictor.netty.netty_protobuf.MyMessage.DataType data_type = 1;</code>
       */
      public com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType result = com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType.valueOf(dataType_);
        return result == null ? com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType.PersonType : result;
      }
      /**
       * <code>required .com.ssvictor.netty.netty_protobuf.MyMessage.DataType data_type = 1;</code>
       */
      public Builder setDataType(com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.ssvictor.netty.netty_protobuf.MyMessage.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.ssvictor.netty.netty_protobuf.DataInfo.Teacher, com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.Builder, com.ssvictor.netty.netty_protobuf.DataInfo.TeacherOrBuilder> teacherBuilder_;
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
       */
      public boolean hasTeacher() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
       */
      public com.ssvictor.netty.netty_protobuf.DataInfo.Teacher getTeacher() {
        if (teacherBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_;
          }
          return com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return teacherBuilder_.getMessage();
          }
          return com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
       */
      public Builder setTeacher(com.ssvictor.netty.netty_protobuf.DataInfo.Teacher value) {
        if (teacherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          teacherBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
       */
      public Builder setTeacher(
          com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.Builder builderForValue) {
        if (teacherBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          teacherBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
       */
      public Builder mergeTeacher(com.ssvictor.netty.netty_protobuf.DataInfo.Teacher value) {
        if (teacherBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.getDefaultInstance()) {
            dataBody_ = com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.newBuilder((com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            teacherBuilder_.mergeFrom(value);
          }
          teacherBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
       */
      public Builder clearTeacher() {
        if (teacherBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          teacherBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
       */
      public com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.Builder getTeacherBuilder() {
        return getTeacherFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
       */
      public com.ssvictor.netty.netty_protobuf.DataInfo.TeacherOrBuilder getTeacherOrBuilder() {
        if ((dataBodyCase_ == 2) && (teacherBuilder_ != null)) {
          return teacherBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_;
          }
          return com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Teacher teacher = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ssvictor.netty.netty_protobuf.DataInfo.Teacher, com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.Builder, com.ssvictor.netty.netty_protobuf.DataInfo.TeacherOrBuilder> 
          getTeacherFieldBuilder() {
        if (teacherBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.getDefaultInstance();
          }
          teacherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ssvictor.netty.netty_protobuf.DataInfo.Teacher, com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.Builder, com.ssvictor.netty.netty_protobuf.DataInfo.TeacherOrBuilder>(
                  (com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return teacherBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.ssvictor.netty.netty_protobuf.DataInfo.Student, com.ssvictor.netty.netty_protobuf.DataInfo.Student.Builder, com.ssvictor.netty.netty_protobuf.DataInfo.StudentOrBuilder> studentBuilder_;
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
       */
      public boolean hasStudent() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
       */
      public com.ssvictor.netty.netty_protobuf.DataInfo.Student getStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_;
          }
          return com.ssvictor.netty.netty_protobuf.DataInfo.Student.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return studentBuilder_.getMessage();
          }
          return com.ssvictor.netty.netty_protobuf.DataInfo.Student.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
       */
      public Builder setStudent(com.ssvictor.netty.netty_protobuf.DataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
       */
      public Builder setStudent(
          com.ssvictor.netty.netty_protobuf.DataInfo.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
       */
      public Builder mergeStudent(com.ssvictor.netty.netty_protobuf.DataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.ssvictor.netty.netty_protobuf.DataInfo.Student.getDefaultInstance()) {
            dataBody_ = com.ssvictor.netty.netty_protobuf.DataInfo.Student.newBuilder((com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            studentBuilder_.mergeFrom(value);
          }
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
       */
      public com.ssvictor.netty.netty_protobuf.DataInfo.Student.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
       */
      public com.ssvictor.netty.netty_protobuf.DataInfo.StudentOrBuilder getStudentOrBuilder() {
        if ((dataBodyCase_ == 3) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_;
          }
          return com.ssvictor.netty.netty_protobuf.DataInfo.Student.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.ssvictor.netty.netty_protobuf.Student student = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ssvictor.netty.netty_protobuf.DataInfo.Student, com.ssvictor.netty.netty_protobuf.DataInfo.Student.Builder, com.ssvictor.netty.netty_protobuf.DataInfo.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.ssvictor.netty.netty_protobuf.DataInfo.Student.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ssvictor.netty.netty_protobuf.DataInfo.Student, com.ssvictor.netty.netty_protobuf.DataInfo.Student.Builder, com.ssvictor.netty.netty_protobuf.DataInfo.StudentOrBuilder>(
                  (com.ssvictor.netty.netty_protobuf.DataInfo.Student) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return studentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ssvictor.netty.netty_protobuf.MyMessage)
    }

    // @@protoc_insertion_point(class_scope:com.ssvictor.netty.netty_protobuf.MyMessage)
    private static final com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage();
    }

    public static com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @java.lang.Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ssvictor.netty.netty_protobuf.DataInfo.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ssvictor.netty.netty_protobuf.Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     */
    int getAge();
  }
  /**
   * Protobuf type {@code com.ssvictor.netty.netty_protobuf.Teacher}
   */
  public  static final class Teacher extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ssvictor.netty.netty_protobuf.Teacher)
      TeacherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teacher() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Teacher();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Teacher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.class, com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ssvictor.netty.netty_protobuf.DataInfo.Teacher)) {
        return super.equals(obj);
      }
      com.ssvictor.netty.netty_protobuf.DataInfo.Teacher other = (com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ssvictor.netty.netty_protobuf.DataInfo.Teacher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ssvictor.netty.netty_protobuf.Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ssvictor.netty.netty_protobuf.Teacher)
        com.ssvictor.netty.netty_protobuf.DataInfo.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Teacher_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.class, com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.Builder.class);
      }

      // Construct using com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Teacher_descriptor;
      }

      @java.lang.Override
      public com.ssvictor.netty.netty_protobuf.DataInfo.Teacher getDefaultInstanceForType() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.getDefaultInstance();
      }

      @java.lang.Override
      public com.ssvictor.netty.netty_protobuf.DataInfo.Teacher build() {
        com.ssvictor.netty.netty_protobuf.DataInfo.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ssvictor.netty.netty_protobuf.DataInfo.Teacher buildPartial() {
        com.ssvictor.netty.netty_protobuf.DataInfo.Teacher result = new com.ssvictor.netty.netty_protobuf.DataInfo.Teacher(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) {
          return mergeFrom((com.ssvictor.netty.netty_protobuf.DataInfo.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ssvictor.netty.netty_protobuf.DataInfo.Teacher other) {
        if (other == com.ssvictor.netty.netty_protobuf.DataInfo.Teacher.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ssvictor.netty.netty_protobuf.DataInfo.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ssvictor.netty.netty_protobuf.DataInfo.Teacher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ssvictor.netty.netty_protobuf.Teacher)
    }

    // @@protoc_insertion_point(class_scope:com.ssvictor.netty.netty_protobuf.Teacher)
    private static final com.ssvictor.netty.netty_protobuf.DataInfo.Teacher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ssvictor.netty.netty_protobuf.DataInfo.Teacher();
    }

    public static com.ssvictor.netty.netty_protobuf.DataInfo.Teacher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Teacher>
        PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
      @java.lang.Override
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teacher(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teacher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ssvictor.netty.netty_protobuf.DataInfo.Teacher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ssvictor.netty.netty_protobuf.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>optional string address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code com.ssvictor.netty.netty_protobuf.Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ssvictor.netty.netty_protobuf.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              address_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ssvictor.netty.netty_protobuf.DataInfo.Student.class, com.ssvictor.netty.netty_protobuf.DataInfo.Student.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 3;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ssvictor.netty.netty_protobuf.DataInfo.Student)) {
        return super.equals(obj);
      }
      com.ssvictor.netty.netty_protobuf.DataInfo.Student other = (com.ssvictor.netty.netty_protobuf.DataInfo.Student) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ssvictor.netty.netty_protobuf.DataInfo.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ssvictor.netty.netty_protobuf.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ssvictor.netty.netty_protobuf.Student)
        com.ssvictor.netty.netty_protobuf.DataInfo.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ssvictor.netty.netty_protobuf.DataInfo.Student.class, com.ssvictor.netty.netty_protobuf.DataInfo.Student.Builder.class);
      }

      // Construct using com.ssvictor.netty.netty_protobuf.DataInfo.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.internal_static_com_ssvictor_netty_netty_protobuf_Student_descriptor;
      }

      @java.lang.Override
      public com.ssvictor.netty.netty_protobuf.DataInfo.Student getDefaultInstanceForType() {
        return com.ssvictor.netty.netty_protobuf.DataInfo.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.ssvictor.netty.netty_protobuf.DataInfo.Student build() {
        com.ssvictor.netty.netty_protobuf.DataInfo.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ssvictor.netty.netty_protobuf.DataInfo.Student buildPartial() {
        com.ssvictor.netty.netty_protobuf.DataInfo.Student result = new com.ssvictor.netty.netty_protobuf.DataInfo.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ssvictor.netty.netty_protobuf.DataInfo.Student) {
          return mergeFrom((com.ssvictor.netty.netty_protobuf.DataInfo.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ssvictor.netty.netty_protobuf.DataInfo.Student other) {
        if (other == com.ssvictor.netty.netty_protobuf.DataInfo.Student.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000004;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ssvictor.netty.netty_protobuf.DataInfo.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ssvictor.netty.netty_protobuf.DataInfo.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 3;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ssvictor.netty.netty_protobuf.Student)
    }

    // @@protoc_insertion_point(class_scope:com.ssvictor.netty.netty_protobuf.Student)
    private static final com.ssvictor.netty.netty_protobuf.DataInfo.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ssvictor.netty.netty_protobuf.DataInfo.Student();
    }

    public static com.ssvictor.netty.netty_protobuf.DataInfo.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ssvictor.netty.netty_protobuf.DataInfo.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ssvictor_netty_netty_protobuf_Teacher_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ssvictor_netty_netty_protobuf_Teacher_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ssvictor_netty_netty_protobuf_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ssvictor_netty_netty_protobuf_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022!com.ssvictor.netty.nett" +
      "y_protobuf\"\215\002\n\tMyMessage\022H\n\tdata_type\030\001 " +
      "\002(\01625.com.ssvictor.netty.netty_protobuf." +
      "MyMessage.DataType\022=\n\007teacher\030\002 \001(\0132*.co" +
      "m.ssvictor.netty.netty_protobuf.TeacherH" +
      "\000\022=\n\007student\030\003 \001(\0132*.com.ssvictor.netty." +
      "netty_protobuf.StudentH\000\"+\n\010DataType\022\016\n\n" +
      "PersonType\020\001\022\017\n\013TeacherType\020\002B\013\n\tdata_bo" +
      "dy\"$\n\007Teacher\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005" +
      "\"5\n\007Student\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\017" +
      "\n\007address\030\003 \001(\tB/\n!com.ssvictor.netty.ne" +
      "tty_protobufB\010DataInfoH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ssvictor_netty_netty_protobuf_MyMessage_descriptor,
        new java.lang.String[] { "DataType", "Teacher", "Student", "DataBody", });
    internal_static_com_ssvictor_netty_netty_protobuf_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ssvictor_netty_netty_protobuf_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ssvictor_netty_netty_protobuf_Teacher_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_com_ssvictor_netty_netty_protobuf_Student_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ssvictor_netty_netty_protobuf_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ssvictor_netty_netty_protobuf_Student_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
